### ISSUE TITLE
kubepug reports an invalid Deprecation

### ISSUE THREAD

**Issue by RudyBone** [rikatz/kubepug#120] opened 2020-10-02 17:37 UTC
Running kubepug against swagger version 1.14.9 against a 1.14.5 cluster  I get list of deprecations against my deployments complaining that my deployments are found in extensions/v1beta1  which is simply not true.  ALL of my deployment yamls specify apps/v1 as the apiVersion.  Are you running kubectl under the covers because kubectl makes the same mistake when I do:

kubectl get deployments -o yam --v==8

In this case kubectl uses the extensions/v1beta1 API 

My own java REST api uses the apps/v1 api when getting a list of deployments and all my deployments com back with that API.  Any idea what's going on here?

**Comment by rikatz** [comment] 2020-10-03 01:24
Yes, I do not run kubectl under the hood, but I use client-go which uses the returned preferred apiVersion from the apiServer. 

Kubernetes 1.14 still uses extensions/v1beta1 as preferred API and that's why apiServer will always return deployments this way in this version, even if you create them as apps/v1. 

The same happens today with Ingress in version v1.19 (PTAL https://kubernetes.slack.com/archives/C09QYUH5W/p1599668910140500) 

I'll dig deeper into this issue again maybe on weekend to see if anything else can be done

**Comment by RudyBone** [comment] 2020-10-05 13:17
Ricardo,

I believe you are conflating 'preferred version' with preferred api.  The
former is actually returned in the json spec for a given api; e.g. both the
apps and extensions api's support multiple versions, but only a single
version is preferred for each api; v1 for apps and v1beta1 for extensions.
The only place where I have ever found a 'preferred' API is in the API
Reference pages
https://v1-15.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/
 where the 'preferred' version of Deployments is apps/v1 and the  Older
Versions (apps/v1beta1, apps/v1beta2, and extensions/v1beta1) are listed
further down the page.  I have not been able to find a 'machine readable'
json spec for a preferred api/version.  HOWEVER. the swagger.json files do
mark indicate group version DEPRECATED in the description field
(Technically I don't consider this machine readable since you essentially
have to parse the string to get the DEPRECATED status as well as the
api/version that it was deprecated by).   Speaking of the latter, which is
what I believe kubepug uses to in its Depracated APIs section, you need to
recursively follow the deprecated versions until you find a non-deprecated
version.  For instance, client.go reported my Deployment versions as
extensions/v1beta1 as deprecated and superseded by apps/v1beta2/Deployment
and stopped there.  However if you look up  apps/v1beta2/Deployment in the
same swagger.json file (v1.14.9 in my case), you'll see that that
api/version is ALSO DEPRECATED in favor of apps/v1.  Which in fact is what
my Deployments were deployed as.

**Comment by rikatz** [comment] 2020-10-06 14:11
hum I promise will take a look this week(end) :)

Thank you for reporting!

**Comment by rikatz** [comment] 2020-10-30 19:22
Hello, sorry for the long delay. I've been caught in some other current job issues :/

**Comment by TheKangaroo** [comment] 2021-01-12 11:16
I have a very similar issue (if not the same)to this one, https://github.com/rikatz/kubepug/issues/72 / https://github.com/rikatz/kubepug/issues/79 . 
Let me explain with an example:
I get a bunch of warnings when running `kubectl deprecations` on my 1.17 cluster, so i dug into the first ingress object.
It turned out, I can
```
kubectl get ingresses.networking.k8s.io
```
and
```
kubectl get ingresses.extensions (deprecated)
```
and both return the same object (via diffrent APIs, e.g. `apiVersion: networking.k8s.io/v1beta1` and `apiVersion: extensions/v1beta1`).

The problem is, kubernetes does this for newer and older APIs. This means it does not matter if I initially deployed this ingress object via `networking` or `extensions` API. 
But thats basically what I need to know. I mean I do know, that my kubernetes cluster supports the deprecated `extentsions` api for ingress. What I need to know is which API was used to create this object.

As far as I can tell, there is no way to know, which API was used to create an k8s object besides the last applied annotation (which isn't suitable for this use case, e.g. https://github.com/rikatz/kubepug/issues/79#issuecomment-643803154 ).

The only way to check, if I use deprecated APIs is by parsing the yaml files in the first place.

Please let me know if I'm wrong here, I would love to have a tool to check against a live cluster for deprecated API usage.

**Comment by fewkso** [comment] 2021-02-04 13:45
I ran "kubepug --k8s-version=v1.16.15" against many 1.15.12 clusters and all extensions/v1beta1 resources show up as deprecated and not deleted.

I don't know if this is caused by 1.15 supporting both apps/v1 and extensions/v1beta1 apis but it cause bad surprises since all seemed well and k8s was updated without any problems and everything kept working afterward, until we tried to update helm charts.

Since helm charts releases are kept in secrets to track what it installed, it won't allow updates since apiVersion changed in templates to match k8s 1.16 apiVersions. We need to helm delete then reinstall those charts, to make sure we don't lost any data we have to make sure all PVs are set to retain.

I hope it helps others in the same situation.

**Comment by rikatz** [comment] 2021-02-04 13:50
hey folks.

I'm really sorry about taking that long to answer this issue here, I'm crowded with some things of my day job.

@fewkso thank you for the heads up. What happens usually is that the apiServer returns a prefered version, which might be different from what pug considers stable or deprecated.

I'll take a look to see how to evolve this

Thank you all for reporting and sorry again for the long delays

**Comment by ninlil** [comment] 2021-05-06 13:36
This issue is really annoying (and tricky to solve, i've tried as well)

I'm instead using the following command/script:
```
kubectl get ingress -A -o go-template='{{range .items}}{{if index .metadata.annotations "kubectl.kubernetes.io/last-applied-configuration"}}{{index .metadata.annotations "kubectl.kubernetes.io/last-applied-configuration"}}{{"\n"}}{{end}}{{end}}' | \
                jq -r '[.kind, .metadata.namespace, .metadata.name, .apiVersion] | @tsv' | column -c 4 -t
```
This lists the ingresses (swap type to whatever you want) and extracts the apiVersion from the last-applied-configuration for each resource

**Comment by Monta89** [comment] 2021-10-17 20:19
has this issue been resolved ?

**Comment by fredgate** [comment] 2021-11-25 11:08
> kubectl get ingress -A -o go-template='{{range .items}}{{if index .metadata.annotations "kubectl.kubernetes.io/last-applied-configuration"}}{{index .metadata.annotations "kubectl.kubernetes.io/last-applied-configuration"}}{{"\n"}}{{end}}{{end}}' | \
>                 jq -r '[.kind, .metadata.namespace, .metadata.name, .apiVersion] | @tsv' | column -c 4 -t

This works only for resources installed with kubectl, but not for them installed with Helm.

**Comment by rikatz** [comment] 2021-11-28 23:59
gonna look this next :)

**Comment by rikatz** [comment] 2021-11-29 00:08
@fredgate Thanks for the idea. Using the annotations actually is "bad", as far as I remember those are used via kubectl apply (but not via kubectl create, as an example).

@RudyBone seems reasonable, following the swagger JSON spec until you find the right version. I remember that there is something (need to read here again on the kubernetes api spec) that turns different what you get from the API server from what is actually persisted in etcd (@cpanato may remind as well, but I will take a look into some docs here).

I need to run some scenarios, where I do add something "deprecated" (like in version v1.14) and then try to migrate to version 1.16. IIRC while the API is not removed, something internally converts this to the right version in ETCD but I'm not quite sure right now :/

Anyway, let me look here into swagger.json and what can be done :)

**Comment by rikatz** [comment] 2021-11-29 01:51
swagger.json wont be helpful in this case.

@RudyBone I remember now, that the idea of PreferredResources is what the APIServer will serve preferentially, even if it is deprecated.

I'm still looking into the Discovery Library (https://pkg.go.dev/k8s.io/client-go/discovery) to see if there is some way of fixing this, but as far as I remember preferred versions comes from: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/aggregator.go#L247

I will keep looking into it during the week :)

**Comment by marafa-sugarcrm** [comment] 2022-06-29 09:11
any update on this?

**Comment by rikatz** [comment] 2023-07-04 17:00
I have released a new version today. The PreferredServerVersion is the decision point on if something is deprecated or not. If you are using, for instance, v1.X and it says the preferred version for apps API is /v1beta1, and you try to check against v1.Y , it will raise an alert that this is deprecated.

The deprecation notice is just a "Warning" that if you migrate to this other release, the API version will be migrated internally.

The deleted error is more dangerous, as it means that the API you are currently using is not served anymore on the version you are targetting, so you will need to do a stepped update to some release that supports both, and then move to the final release.

I'm closing thius, but feel free to reopen or ping me on Slack

**Closed by rikatz** 2023-07-04 17:00 UTC
