### ISSUE TITLE
kubepug doesn't find deprecated batch/v1beta1 CronJob API

### ISSUE THREAD

**Issue by peterjanes** [rikatz/kubepug#225] opened 2022-01-12 16:00 UTC
`kubepug -k8s-version v1.21.0 --input-file deprecated-cronjob.yaml --error-on-deleted --error-on-deprecated` passes for this file (using `v1.21.0`, `v1.22.0`, and `v1.23.0`) but when deploying it to a v1.21.0 cluster I get the warning `Warning: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob`.

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: foo
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: foo
            image: ...
          restartPolicy: Never
  schedule: 0 0 0 0 0
```

**Comment by peterjanes** [comment] 2022-01-12 16:21
With --verbosity debug:

```
time="2022-01-12T11:02:59-05:00" level=debug msg="Adding batch/v1beta1/CronJob to map. Deprecated: false" func=github.com/rikatz/kubepug/pkg/parser.KubernetesAPIs.PopulateKubeAPIMap file="github.com/rikatz/kubepug/pkg/parser/parser.go:58"
```

Looks like the Swagger files [up to v1.23.0](https://raw.githubusercontent.com/kubernetes/kubernetes/v1.23.0/api/openapi-spec/swagger.json) don't include the "deprecated" string.

**Comment by soichisumi** [comment] 2022-01-13 23:37
Is it still difficult to fully trust the output of kubepug as conversed in the issue?

**Comment by rikatz** [comment] 2022-01-14 12:13
Hi, I will look at this during the weekend. If something changed in openapispec of v1.23, I will need to re-write those logics.

About fully trusting the output, it's also hard for me :) I rely on strings that may or may not exist, depending on who implemented that on Kubernetes API side. 

Kubepugs idea was mostly using those openapi spec descriptions as a way (but not the only way) to get deprecated objects on the cluster, but by that time it was really hard as we don't have a "flag/bool" in openapi spec saying that a field is deprecated or not :/

I know there are some issues here and I will cycle back asap

**Comment by soichisumi** [comment] 2022-01-15 04:48
I saw https://github.com/kubernetes/kubernetes/issues/107498

I see that there is no information in the current schema that can reliably determine if it is deprecated or not, and it relies on the description. I understand the difficulty.
I'm looking forward to kubepug getting better and being able to bool deprecation information into schema!

**Comment by rikatz** [comment] 2023-07-04 16:58
Apparently this is how swagger.json was generated. I was reading the mentioned issue, but pointing to openapiv3 won't be helpful (in fact, the API will be detected as DELETED as there's no batch/v1beta1 anymore: https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec/v3)

Can you check with the latest release, anyway, if something changes on the detection? (There's a new alpha release from today).

Thanks

**Comment by peterjanes** [comment] 2023-07-04 22:25
When executed against 1.26.0 it catches the deleted API as expected; no change running against 1.21.0, also as expected.

**Comment by rikatz** [comment] 2023-07-04 23:14
ok great. So I will close this issue, as it is working for v1.26 but we cannot catch today the deprecation on other APIs due to swagger not containing the right information, ok?

But please feel free to reopen it, or reach me on Kubernetes slack.

thanks!

**Closed by rikatz** 2023-07-04 23:14 UTC

**Comment by rikatz** [comment] 2023-07-04 23:22
Just confirmed that the specv3 contains CronJob as v1beta1 but also no indication it is deprecated :( 

So there's no way today to verify it.
