### ISSUE TITLE
Not detecting Deprecated API CronJob

### ISSUE THREAD

**Issue by tpsimoes** [rikatz/kubepug#282] opened 2022-08-26 17:59 UTC
tpsimoes  ~/cluster-ing-121  kubectl get --raw=/apis/batch/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"batch/v1beta1","resources":[{"name":"cronjobs","singularName":"","namespaced":true,"kind":"CronJob","verbs":["create","delete","deletecollection","get","list","patch","update","watch"],"shortNames":["cj"],"categories":["all"],"storageVersionHash":"h/JlFAZkyyY="},{"name":"cronjobs/status","singularName":"","namespaced":true,"kind":"CronJob","verbs":["get","patch","update"]}]}

 tpsimoes  ~/cluster-ing-121  kubectl deprecations --k8s-version=v1.25.0
W0826 18:58:40.671903    3078 warnings.go:70] v1 ComponentStatus is deprecated in v1.19+
W0826 18:58:40.935500    3078 warnings.go:70] apiregistration.k8s.io/v1beta1 APIService is deprecated in v1.19+, unavailable in v1.22+; use apiregistration.k8s.io/v1 APIService
W0826 18:58:41.096370    3078 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0826 18:58:41.149726    3078 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0826 18:58:41.197920    3078 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
RESULTS:
Deprecated APIs:

ComponentStatus found in /v1
         ├─ ComponentStatus (and ComponentStatusList) holds the cluster validation info. Deprecated: This API is deprecated in v1.19+
                -> GLOBAL: scheduler
                -> GLOBAL: controller-manager
                -> GLOBAL: etcd-0

Deleted APIs:

Ingress found in extensions/v1beta1
         ├─ API REMOVED FROM THE CURRENT VERSION AND SHOULD BE MIGRATED IMMEDIATELY!!
                -> OBJECT: aspnetapp namespace: default
                -> OBJECT: test-ingress namespace: default
                -> OBJECT: go-server-ingress-bkprefix namespace: test-ag

**Comment by rikatz** [comment] 2023-07-04 16:47
Can you test with https://github.com/rikatz/kubepug/releases/tag/v1.5.0-alpha.0  please?

Thanks!

**Comment by rikatz** [comment] 2023-07-04 20:19
/close
Duplicate of #225, thanks for reporting!

**Closed by rikatz** 2023-07-04 20:19 UTC
